INSERT INTO TBL_CATEGORY (NAME) VALUES ('Produção Própria');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Nacional');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Importado');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Premium');